spring:
  application:
    name: glucose-monitor-be
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/glucose_monitor}
    username: ${DB_USERNAME:glucose_monitor_user}
    password: ${DB_PASSWORD:glucose}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Use Flyway for migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET:very-strong-secret-change-me-please-make-it-long-and-secure-in-production}
    access-expiration-ms: 3600000      # 1 hour
    refresh-expiration-ms: 86400000    # 24 hours

server:
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        tool:
          schema: DEBUG
      springframework:
        orm:
          jpa: DEBUG

app:
  features:
    backend-mode-enabled: true
    insulin-calculator-enabled: true
    carbs-on-board-enabled: true
    glucose-data-enabled: false
    user-configuration-enabled: false

    # Migration percentages (0-100)
    insulin-calculator-migration-percent: 25
    carbs-on-board-migration-percent: 25
    glucose-data-migration-percent: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always