spring:
  application:
    name: glucose-monitor-be
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/glucose_monitor}
    username: ${DB_USERNAME:glucose_monitor_user}
    password: ${DB_PASSWORD:glucose}
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: ${TZ:Europe/London}  # Use user's timezone, default to London
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  jpa:
    hibernate:
      ddl-auto: validate  # Use Flyway for migrations
    show-sql: true
    open-in-view: false  # Disable to prevent lazy loading issues
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cloud:
    compatibility-verifier:
      enabled: false

security:
  jwt:
    secret: ${JWT_SECRET:very-strong-secret-change-me-please-make-it-long-and-secure-in-production}
    access-expiration-ms: 3600000      # 1 hour
    refresh-expiration-ms: 86400000    # 24 hours

server:
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        tool:
          schema: DEBUG
      springframework:
        orm:
          jpa: DEBUG

app:
  version:
    version: "1.0.0"
    api-version: "v1"
    build-number: ${BUILD_NUMBER:dev-build}
    git-commit: ${GIT_COMMIT:unknown}
    build-time: ${BUILD_TIME:}
    min-frontend-version: "1.0.0"
    compatible-frontend-versions:
      - "1.0.0"
      - "1.0.1" 
      - "1.1.0"
    feature-versions:
      glucose-calculations: "1.0.0"
      insulin-calculator: "1.0.0"
      carbs-on-board: "1.0.0"
      notes-api: "1.0.0"
      auth-system: "1.0.0"
    deprecated-versions:
      "0.9.0": "Please upgrade to 1.0.0 - contains critical security fixes"
      "0.8.0": "Version no longer supported - upgrade required"
  
  features:
    # Enable backend calculations with timezone support
    backend-mode-enabled: true
    insulin-calculator-enabled: true
    carbs-on-board-enabled: true
    glucose-data-enabled: false
    glucose-calculations-enabled: true
    user-configuration-enabled: false

    # Migration percentages (0-100) - 100 means all users use backend
    insulin-calculator-migration-percent: 100
    carbs-on-board-migration-percent: 100
    glucose-data-migration-percent: 100
    glucose-calculations-migration-percent: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# CORS configuration for development
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001}

# Nightscout configuration
nightscout:
  base-url: ${NIGHTSCOUT_BASE_URL:https://vladchernichenko.eu.nightscoutpro.com}
  api-secret: ${NIGHTSCOUT_API_SECRET:}
  token: ${NIGHTSCOUT_TOKEN:}